POST http://localhost:3000/api
Content-Type: application/json

{
    "volt":51,
    "amp":51
}

###
GET http://localhost:3000/api

###
DELETE  http://localhost:3000/api
Content-Type: application/json

{
    "startDay": "2021-11-07 16:21:36" ,
    "endDay": "2021-11-07 16:22:" 
}

###
DELETE  http://localhost:3000/logout
